#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in Modulefile
#modulefile

# Puppet Supported Modules
# https://forge.puppetlabs.com/supported
mod 'puppet-selinux', '1.6.1'
mod 'puppetlabs-stdlib', '5.1.0'
mod 'puppetlabs-firewall', '1.14.0'
mod 'puppetlabs-java', '3.2.0'
mod 'puppetlabs-apache', '3.5.0'

#mod 'puppetlabs/concat'
#mod 'puppetlabs/inifile'
#mod 'puppetlabs/tomcat'

# Puppet Approved Modules
# https://forge.puppetlabs.com/approved
mod 'maestrodev/wget'
mod 'rodjek/logrotate'

mod 'bstopp-aem', '2.6.1'
